apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudvibes-weather-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Tokoynwa/Weather.git
    targetRevision: dev
    path: k8s/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudvibes-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
